name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 3.0
          ar_version: 6.1.0
        - ruby: 2.7
          ar_version: 6.0.0
    runs-on: ubuntu-latest
    env:
      AR_VERSION: ${{ matrix.ar_version }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake test
